Repository EddieDover/fvtt-party-sheet, pull requests merged in 2024-08, with the labels that each got.

#39 [Feature Request] Add support for rowspan
  TEMPLATE_README.md
  src/module/app/party-sheet.js
  src/module/fvtt-party-sheet.js
  src/templates/party-sheet.hbs
Labels: enhancement, user request

#34 [Feature Request] Allowing especial character display for Font Awesome
  TEMPLATE_README.md
  src/module/utils.js
  test/utils.test.js
Labels: enhancement, user request

#30 [Feature request] Support for default + in positive numbers
  TEMPLATE_README.md
  example_templates/dnd5e/dnd5e_modified.json
  src/module/app/party-sheet.js
  src/module/utils.js
  test/utils.test.js
Labels: enhancement, user request

#35 feat(schema): added schema for templates
  .vscode/settings.json
  .vscode/template.schema.json
Labels: documentation

#36 feat(template): added pf1 template
  TEMPLATE_LIST.md
  example_templates/pf1/pf1-template.json
  example_templates/pf1/pf1.png
Labels: template updates
